Repository qaidjoharj53/Student-Management-System, pull requests merged in 2023-10, with the labels that each got.

#2 Documentation qaidjoharj53
  Contributing.md
  code_of_conduct.md
Labels: documentation, good first issue, Hacktoberfest-accepted

#3 Updated the README.md File
  README.md
Labels: documentation, good first issue, Hacktoberfest-accepted

#7 format the code and increase the readibility
  .vscode/settings.json
  CS_Source Code.py
Labels: enhancement, Hacktoberfest-accepted

#8 Create python-app.yml
  .github/workflows/python-app.yml
Labels: documentation, Hacktoberfest-accepted

#9 Added GUI for the Application
  CS_Source Code.py
  GUI/__pycache__/file_operations.cpython-311.pyc
  GUI/__pycache__/student.cpython-311.pyc
  GUI/file_operations.py
  GUI/gui.py
  GUI/stud.dat
  GUI/student.py
  stud.dat
Labels: enhancement, Hacktoberfest-accepted

#12 Dat-removal
  CS_Source Code.py
  README.md
  create_dat.py
Labels: enhancement, Hacktoberfest-accepted

#15 pickle to mysql
  mysql/CS_Source Code.py
  mysql/create_data.py
Labels: enhancement, Hacktoberfest-accepted

#14 adding project files
  .gitignore
  create_dat.py
  models.py
  requirements.txt
Labels: documentation, Hacktoberfest-accepted

#19 cls else clear
  CS_Source Code.py
Labels: bug, Hacktoberfest-accepted
